pangtao22/quasistatic_simulator

examples/allegro_hand/allegro_hand_sliders.ipynb
examples/allegro_hand/run_allegro_hand.py
examples/iiwa_block_stacking/tests/test_iiwa_block_stacking.py
examples/planar_hand_ball/run_planar_hand.py
examples/planar_hand_ball/test_python_vs_cpp_manual.py
examples/setup_simulations.py
examples/two_spheres_y/run_two_spheres_1d.py
examples/two_spheres_yz/run_planar_pushing.py
models/allegro_hand.yml
models/allegro_hand_description_right_spheres.sdf
models/q_sys/allegro_hand_and_sphere.yml
models/q_sys/planar_hand_ball.yml
models/sphere_r0.05m.sdf
models/sphere_r0.06m.sdf
qsim/parser.py
qsim/simulator.py
traj_opt/trajectory_optimization.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/9)

Allegro hand simulation.

---

.gitignore
qsim/parser.py

Adds factory function for `BatchQuasistaticSimulaotr` in `QuasistaticParser`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/10)

Batch simulator

---

models/q_sys/box_pushing.yml
models/q_sys/planar_hand_ball_small_ball.yml
models/sphere_yz_rotation_r_0.125m.sdf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/12)

add small ball-hand and box pushing environment to q_sys

---

models/box_to_push.sdf
models/box_to_push_xy_rotation.sdf
models/iiwa14_sphere_collision_push.sdf
models/iiwa_sphere_collision_push.yml
models/iiwa_sphere_collision_push_no_ground.yml
models/q_sys/iiwa_box.yml
models/q_sys/iiwa_box_no_ground.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/27)

Add Aykut's iiwa_push model files.

---

models/box_y.sdf
models/cylinder.sdf
models/q_sys/iiwa_bimanual_cylinder.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/29)

small changes to models.

---

quasistatic_simulator_cpp/src/log_barrier_solver.cc
quasistatic_simulator_cpp/src/test_log_barrier_solver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/32)

use gurobi solver for gurobi solver pointer in LogBarrierSolver.

---

.github/workflows/delete_pr_image_on_merge.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/44)

Keep testing CI

---

.github/workflows/delete_pr_image_on_merge.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/47)

keep trying

---

.github/workflows/delete_pr_image_on_merge.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/49)

A few more changes to ghcr pruning workflow.

---

.github/workflows/delete_pr_image_on_merge.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/50)

not a dry run.

---

.github/workflows/build_push_prune.yml
.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/52)

Bug fix in merge workflow.

---

.github/workflows/build_push_prune.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/54)

merge workflow bug fix.

---

.github/workflows/build_push_prune.yml
.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/55)

Merge workflow fix.

---

quasistatic_simulator_cpp/src/batch_quasistatic_simulator.h

Addresses #42
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/57)

Add #include <threads> to batch simulator.

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/59)

Use the correct docker image tag in merge events. 

---

.github/workflows/ci.yml
setup/run_tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/60)

test changes in /setup

---

.github/workflows/build_push_prune.yml
.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/61)

reenable tests in CI.

---

.github/workflows/build_push_prune.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/64)

less frequent prune.

---

setup/base.dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/70)

Updrake to 1.18.0

---

qsim/parser.py
quasistatic_simulator_cpp/bindings/qsim_cpp.cc
quasistatic_simulator_cpp/examples/run_3link_arm_3d.cc
quasistatic_simulator_cpp/examples/run_iiwa_box_stacking.cc
quasistatic_simulator_cpp/examples/run_planar_hand_ball.cc
quasistatic_simulator_cpp/qsim/batch_quasistatic_simulator.cc
quasistatic_simulator_cpp/qsim/batch_quasistatic_simulator.h
quasistatic_simulator_cpp/qsim/finite_differencing_gradient.cc
quasistatic_simulator_cpp/qsim/finite_differencing_gradient.h
quasistatic_simulator_cpp/qsim/quasistatic_parser.cc
quasistatic_simulator_cpp/qsim/quasistatic_simulator.cc
quasistatic_simulator_cpp/qsim/quasistatic_simulator.h
quasistatic_simulator_cpp/tests/test_quasistatic_sim_gradients.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pangtao22/quasistatic_simulator/72)

Batch Finite Differencing
